### ISSUE TITLE
Extended SASL support

### ISSUE THREAD

**Issue by pokryva** [emrebekar/node-red-contrib-kafkajs#2]
Hi,
Do you have plans to support other SASL authentication methods other than SIMPLE (like SCRAM-SHA-256, SCRAM-SHA-512) - seems that kafkajs is supporting those.

**Comment by emrebekar** [comment]
Did you try to connect with sasl plain auth?

**Comment by pokryva** [comment]
Yes, I did try it and it does not work. The node throws the following error message: "The broker does not support the requested SASL mechanism"

**Comment by emrebekar** [comment]
Firstly you have to configure your broker in order to connect over SASL authentication.

**Comment by pokryva** [comment]
Hi, sorry, but perhaps I did not make myself clear. The broker is fine, it just requires SASL_SSL/SCRAM-SHA-512 authentication. I was able to connect to it using node-red-contrib-rdkafka-secure, but for reasons that are irrelevant here - I don't want to use it. That's why I'm looking for other Kafka node that will support the beforementioned authentication...

So I guess the question remains: does/will your node support SASL_SSL/SCRAM-SHA-512 authentication? :)

**Comment by rym002** [comment]
@emrebekar I created a PR #3 to support  [PLAIN, SCRAM-SHA-256 & SCRAM-SHA-512](https://kafka.js.org/docs/configuration#plain-scram-example)

**Comment by emrebekar** [comment]
@rym002 has developed a improvement. @pokryva i have merged the pull request.

**Comment by rym002** [comment]
@emrebekar Any idea when you will release the new version of the node?

**Comment by pokryva** [comment]
Hi I have tested the improvement against my Kafka setup (SASL/SCRAM-SHA-512) and it seems to work. I am also waiting for the release then.

@rym002 @emrebekar  good job!

**Comment by emrebekar** [comment]
Ok i will publish it to npm.

**Comment by pokryva** [comment]
> Ok i will publish it to npm.

Hi, I don't want to sound too impatient, but what's your ETA on releasing the new version to npm? :)

**Comment by emrebekar** [comment]
I have published the new version of kafka node with 0.0.7 tag

**Comment by pokryva** [comment]
Will the updated version show up in Palette Manager?

**Comment by emrebekar** [comment]
It will be shown in pallette upcoming minutes. I have update the nodered registry

**Comment by pokryva** [comment]
Looks good! Thanks again!
